/**
 * Render the filled `agenc.config.ts` from the scaffold options (PLAN_2 C4). The
 * output is a clean, fully-commented config a deployer can keep editing — NOT a
 * minified blob. Curation differs by variant (the C1 rule: the variants differ
 * only in routing + curation).
 *
 * @module render
 */
import type { ScaffoldOptions, TemplateVariant } from "./config.js";

/** JSON-stringify a string for embedding in a TS literal (handles quotes). */
function s(value: string): string {
  return JSON.stringify(value);
}

/** Render the curation block for the chosen variant. */
function curationBlock(opts: ScaffoldOptions): string {
  const lines: string[] = ["  curation: {"];
  if (opts.variant === "provider-storefront") {
    const pda = opts.providerPda ?? opts.referrerWallet;
    lines.push(
      "    // SINGLE PROVIDER — only this provider agent PDA's listings are carried.",
      `    providers: [${s(pda)}],`,
    );
  }
  if (opts.variant === "vertical-store") {
    const cat = opts.category ?? "code-generation";
    lines.push(
      "    // ONE CATEGORY — only listings in this category token are carried.",
      `    categories: [${s(cat)}],`,
    );
  }
  lines.push(
    "    requireModeration: true,",
    "  },",
  );
  return lines.join("\n");
}

/** A short per-variant header comment. */
function variantHeader(variant: TemplateVariant): string {
  switch (variant) {
    case "marketplace-store":
      return "marketplace-store = the FULL catalog variant (grid + categories + search).";
    case "provider-storefront":
      return "provider-storefront = the SINGLE-PROVIDER variant (\"my agency's agents\").";
    case "vertical-store":
      return "vertical-store = the ONE-CATEGORY variant (the D3 verticals launch on this).";
  }
}

/**
 * Render the complete `agenc.config.ts` body for a scaffolded store.
 *
 * @param opts - The validated scaffold options.
 * @returns The file contents.
 */
export function renderAgencConfig(opts: ScaffoldOptions): string {
  // Only emit allowMainnet when the human made the deliberate real-funds
  // opt-in. Never derive it from `network === "mainnet"` alone — that would
  // re-introduce the silent gate bypass (a generated real-funds store the
  // deployer never consciously opted into).
  const mainnetLine = opts.allowMainnet
    ? "\n  allowMainnet: true, // real-funds mainnet opt-in (you passed --allow-mainnet)\n"
    : "";

  return `/**
 * agenc.config.ts — THE single configuration surface for this store (PLAN_2 C2).
 *
 * This is the ONLY file you edit. Curation, branding, SEO, and the referral fee
 * all live here; the template's page code is layout-only and never touches
 * protocol logic. \`defineStore\` validates this at build time and FAILS the build
 * with an actionable message on any misconfiguration.
 *
 * ${variantHeader(opts.variant)}
 *
 * Generated by create-agenc-store.
 */
import { defineStore } from "@tetsuo-ai/store-core/config";

export default defineStore({
  name: ${s(opts.storeName)},
  description: ${s(opts.description)},
${mainnetLine}  network: ${s(opts.network)},

  api: {
    baseUrl: ${s(opts.apiBaseUrl)},
    // apiKey: process.env.AGENC_API_KEY,
  },

  // EVERY hire pays this referral wallet — referral settlement is live
  // on-chain; the fee is validated at build time, injected into each hire
  // automatically, and disclosed on /trust + checkout.
  referrer: {
    wallet: ${s(opts.referrerWallet)},
    feeBps: ${opts.referrerFeeBps}, // shares the protocol+operator+referrer <= 4000 bps cap
  },

  branding: {
    poweredBy: ${opts.poweredBy ? "true" : "false"}, // doubles as the referral disclosure
  },

${curationBlock(opts)}

  payments: {
    wallets: true,
  },

  // WHOSE moderation records this store consumes at the hire gate — the
  // cross-node trust choice. Either way the on-chain gates stay the
  // enforcement point and BLOCKED verdicts fail closed:
  //  - "edge-list" (the default): only records by this store's OWN attestor
  //    (the marketplace-managed service, or your \`attestorEndpoint\` /
  //    \`moderator\` override). Cross-node listings stay un-hireable until
  //    your attestor re-attests them.
  //  - "any-bonded-attestor": the on-chain attestor roster is the trust
  //    root — a CLEAN record by ANY bonded, non-exiting roster attestor
  //    makes a listing hireable here. Choose this to hire cross-node supply
  //    (listings attested by another marketplace's attestor) without
  //    re-attestation.
  // This explicit value wins over the AGENC_MODERATION_TRUST deploy env.
  moderation: {
    trustPolicy: "edge-list",
  },

  seo: {
    siteUrl: ${s(opts.siteUrl)},
    jsonLd: true,
    sitemap: true,
    llmsTxt: true,
  },
});
`;
}

/** Render a `.env.example` for the scaffolded store. */
export function renderEnvExample(): string {
  return `# Optional hosting overrides — everything else lives in agenc.config.ts.

# Override the gPA fallback RPC endpoint (defaults per network).
# AGENC_RPC_URL=

# The hosted-indexer API key (X-Agenc-Api-Key). Anonymous reads work without it.
# AGENC_API_KEY=
`;
}
